version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: smartinfra
      MYSQL_ROOT_PASSWORD: 123456

  smartsalt:
    image: docker.com/probe/smartsalt:v3
    container_name: smartsalt
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env