# Generated by Django 5.1.3 on 2024-11-13 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0003_acl_manage_resource_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_all_relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acl_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.acl_manage')),
                ('rg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.resource_group')),
                ('salt_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.salt_master')),
                ('user_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
