# Generated by Django 5.1.3 on 2024-11-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0004_user_all_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_all_relationship',
            name='salt_id',
        ),
        migrations.AddField(
            model_name='resource_group',
            name='salt',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.salt_master'),
        ),
    ]
