# Generated by Django 5.1.3 on 2024-11-14 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0005_remove_user_all_relationship_salt_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rg_relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rg', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.resource_group')),
                ('salt', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.salt_master')),
            ],
        ),
    ]
