# Generated by Django 5.1.3 on 2024-11-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0006_rg_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_group',
            name='salt',
        ),
    ]
