# Generated by Django 5.1.3 on 2024-11-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0007_remove_resource_group_salt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_all_relationship',
            old_name='acl_id',
            new_name='acl',
        ),
        migrations.RenameField(
            model_name='user_all_relationship',
            old_name='rg_id',
            new_name='rg',
        ),
        migrations.RenameField(
            model_name='user_all_relationship',
            old_name='user_id',
            new_name='user',
        ),
    ]
