# Generated by Django 5.1.3 on 2024-11-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0008_rename_acl_id_user_all_relationship_acl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rg_relationship',
            name='acl',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.acl_manage'),
        ),
    ]
