# Generated by Django 5.1.3 on 2024-11-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0009_rg_relationship_acl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_all_relationship',
            name='acl',
        ),
    ]
