# Generated by Django 5.1.3 on 2024-11-15 22:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0010_remove_user_all_relationship_acl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_all_relationship',
            new_name='user_relationship',
        ),
    ]
