# Generated by Django 5.1.3 on 2024-11-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0011_rename_user_all_relationship_user_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('salt', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.salt_master')),
            ],
        ),
    ]
