# Generated by Django 5.1.3 on 2024-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0012_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (0, 'up')]),
        ),
    ]
