# Generated by Django 5.1.3 on 2024-11-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0013_alter_hosts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (1, 'down'), (2, 'unknown')]),
        ),
    ]
