# Generated by Django 5.1.3 on 2024-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0018_alter_hosts_label_alter_hosts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='label',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (0, 'up')]),
        ),
    ]
