# Generated by Django 5.1.3 on 2024-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0019_alter_hosts_label_alter_hosts_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='label',
            new_name='llabel',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (2, 'unknown'), (1, 'down')]),
        ),
    ]
