# Generated by Django 5.1.3 on 2024-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0020_rename_label_hosts_llabel_alter_hosts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (0, 'up'), (2, 'unknown')]),
        ),
    ]
