# Generated by Django 5.1.3 on 2024-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0021_alter_hosts_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosts',
            old_name='llabel',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (0, 'up'), (1, 'down')]),
        ),
    ]
