# Generated by Django 5.1.3 on 2024-11-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0023_alter_hosts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='label',
        ),
    ]
