# Generated by Django 5.1.3 on 2024-11-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0017_alter_hosts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
