# Generated by Django 5.1.3 on 2024-11-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0024_remove_hosts_label'),
        ('salt', '0025_hosts_label'),
    ]

    operations = [
    ]
