# Generated by Django 5.1.3 on 2024-11-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0026_merge_0024_remove_hosts_label_0025_hosts_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='label',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (2, 'unknown'), (1, 'down')]),
        ),
    ]
