# Generated by Django 5.1.3 on 2024-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0028_alter_hosts_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (0, 'up'), (2, 'unknown')]),
        ),
    ]
