# Generated by Django 5.1.3 on 2024-11-22 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0030_alter_hosts_name_alter_hosts_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='host_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('host_num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (2, 'unknown'), (4, 'denied'), (1, 'down'), (0, 'up'), (3, 'pending')]),
        ),
        migrations.CreateModel(
            name='host_group_minion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minion_name', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host_group_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.host_group')),
            ],
        ),
    ]
