# Generated by Django 5.1.3 on 2024-12-04 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0031_host_group_alter_hosts_status_host_group_minion'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_group_minion',
            name='salt_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.salt_master'),
        ),
        migrations.AlterField(
            model_name='host_group_minion',
            name='minion_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.hosts'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (0, 'up'), (5, 'rejected'), (4, 'denied'), (3, 'pending')]),
        ),
    ]
