# Generated by Django 5.1.3 on 2024-12-06 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0033_host_group_user_alter_hosts_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (1, 'down'), (2, 'unknown'), (4, 'denied'), (5, 'rejected'), (3, 'pending')]),
        ),
        migrations.CreateModel(
            name='task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_content', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execute_policy', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.hosts')),
                ('host_group_name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.host_group')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
