# Generated by Django 5.1.3 on 2024-12-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0034_alter_hosts_status_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(4, 'denied'), (3, 'pending'), (2, 'unknown'), (1, 'down'), (5, 'rejected'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='execute_content',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='execute_policy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
