# Generated by Django 5.1.3 on 2024-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0035_alter_hosts_status_alter_task_list_execute_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (1, '待执行'), (0, '待审批')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (3, 'pending'), (1, 'down'), (2, 'unknown'), (4, 'denied'), (0, 'up')]),
        ),
    ]
