# Generated by Django 5.1.3 on 2024-12-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0037_task_list_execute_result_alter_hosts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='related_schedule',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (5, 'rejected'), (4, 'denied'), (2, 'unknown'), (0, 'up'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (2, '已完成'), (1, '待执行')], default=0),
        ),
    ]
