# Generated by Django 5.1.3 on 2024-12-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0038_task_list_related_schedule_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (0, 'up'), (3, 'pending'), (5, 'rejected'), (4, 'denied'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='execute_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (0, '待审批'), (2, '已完成')], default=0),
        ),
    ]
