# Generated by Django 5.1.3 on 2024-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0039_alter_hosts_status_alter_task_list_execute_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_list',
            name='related_schedule',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (4, 'denied'), (3, 'pending'), (2, 'unknown'), (5, 'rejected'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (2, '已完成'), (1, '待执行')], default=0),
        ),
    ]
