# Generated by Django 5.1.3 on 2024-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0040_remove_task_list_related_schedule_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='related_schedule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (0, 'up'), (2, 'unknown'), (5, 'rejected'), (4, 'denied'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (1, '待执行'), (2, '已完成')], default=0),
        ),
    ]
