# Generated by Django 5.1.3 on 2024-12-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0041_task_list_related_schedule_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (1, 'down'), (3, 'pending'), (0, 'up'), (2, 'unknown'), (4, 'denied')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (2, '已完成'), (1, '待执行'), (0, '待审批')], default=0),
        ),
    ]
