# Generated by Django 5.1.3 on 2024-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0042_alter_hosts_status_alter_task_list_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host_group_minion',
            name='minion_name',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (2, 'unknown'), (3, 'pending'), (4, 'denied'), (0, 'up'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (1, '待执行'), (3, '执行中'), (0, '待审批')], default=0),
        ),
    ]
