# Generated by Django 5.1.3 on 2024-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0043_remove_host_group_minion_minion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_group_minion',
            name='minion_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (0, 'up'), (3, 'pending'), (4, 'denied'), (1, 'down'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (3, '执行中'), (1, '待执行'), (2, '已完成')], default=0),
        ),
    ]
