# Generated by Django 5.1.3 on 2024-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0045_remove_shell_template_content_shell_template_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell_template',
            name='func',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (5, 'rejected'), (1, 'down'), (4, 'denied'), (0, 'up'), (3, 'pending')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (3, '执行中'), (0, '待审批'), (2, '已完成')], default=0),
        ),
    ]
