# Generated by Django 5.1.3 on 2024-12-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0046_shell_template_func_shell_template_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell_template',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (5, 'rejected'), (4, 'denied'), (3, 'pending'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(0, 'state'), (1, 'shell')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (1, '待执行'), (2, '已完成'), (0, '待审批')], default=0),
        ),
    ]
