# Generated by Django 5.1.3 on 2024-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0047_shell_template_file_name_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shell_template',
            old_name='func',
            new_name='func_content',
        ),
        migrations.RenameField(
            model_name='shell_template',
            old_name='main',
            new_name='main_content',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (4, 'denied'), (3, 'pending'), (0, 'up'), (1, 'down'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (3, '执行中'), (2, '已完成'), (1, '待执行')], default=0),
        ),
    ]
