# Generated by Django 5.1.3 on 2024-12-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0048_rename_func_shell_template_func_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt_master',
            name='file_roots',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='minion_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (2, 'unknown'), (1, 'down'), (3, 'pending'), (0, 'up'), (4, 'denied')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (1, '待执行'), (3, '执行中'), (2, '已完成')], default=0),
        ),
    ]
