# Generated by Django 5.1.3 on 2024-12-19 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0049_salt_master_file_roots_salt_master_minion_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (2, 'unknown'), (1, 'down'), (3, 'pending'), (4, 'denied'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (2, '已完成'), (0, '待审批'), (3, '执行中')], default=0),
        ),
        migrations.CreateModel(
            name='general_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=50)),
                ('extra_content', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
