# Generated by Django 5.1.3 on 2024-12-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0050_alter_hosts_status_alter_task_list_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (5, 'rejected'), (3, 'pending'), (4, 'denied'), (2, 'unknown'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(0, 'state'), (1, 'shell')], default=1),
        ),
    ]
