# Generated by Django 5.1.3 on 2024-12-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0051_task_list_name_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='authenticate_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(2, 'OAuth'), (0, 'Internal'), (1, 'LDAP')], default=0)),
                ('client_id', models.CharField(default='', max_length=100)),
                ('client_secret', models.CharField(default='', max_length=200)),
                ('redirect_url', models.CharField(default='', max_length=300)),
                ('user_identifier', models.CharField(default='', max_length=200)),
                ('scopes', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (0, 'up'), (4, 'denied'), (3, 'pending'), (5, 'rejected'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (2, '已完成'), (0, '待审批'), (1, '待执行')], default=0),
        ),
    ]
