# Generated by Django 5.1.3 on 2024-12-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0052_authenticate_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticate_type',
            old_name='scopes',
            new_name='state',
        ),
        migrations.AddField(
            model_name='authenticate_type',
            name='name',
            field=models.CharField(default='authentication', max_length=50),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (1, 'LDAP'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (1, 'down'), (5, 'rejected'), (2, 'unknown'), (4, 'denied'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (3, '执行中'), (0, '待审批'), (1, '待执行')], default=0),
        ),
    ]
