# Generated by Django 5.1.3 on 2024-12-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0053_rename_scopes_authenticate_type_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticate_type',
            name='state',
        ),
        migrations.RemoveField(
            model_name='authenticate_type',
            name='user_identifier',
        ),
        migrations.AddField(
            model_name='authenticate_type',
            name='access_token_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='authenticate_type',
            name='authorization_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'LDAP'), (0, 'Internal'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(4, 'denied'), (1, 'down'), (0, 'up'), (5, 'rejected'), (2, 'unknown'), (3, 'pending')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (2, '已完成'), (1, '待执行'), (3, '执行中')], default=0),
        ),
    ]
