# Generated by Django 5.1.3 on 2024-12-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0054_remove_authenticate_type_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticate_type',
            name='grant_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (2, 'OAuth'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (5, 'rejected'), (4, 'denied'), (0, 'up'), (2, 'unknown'), (3, 'pending')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (0, '待审批'), (3, '执行中'), (2, '已完成')], default=0),
        ),
    ]
