# Generated by Django 5.1.3 on 2025-01-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0057_alter_authenticate_type_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='kernel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'LDAP'), (2, 'OAuth'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (4, 'denied'), (1, 'down'), (5, 'rejected'), (3, 'pending'), (2, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (1, '待执行'), (2, '已完成'), (3, '执行中')], default=0),
        ),
    ]
