# Generated by Django 5.1.3 on 2025-01-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0058_hosts_kernel_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (0, 'Internal'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='kernel',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (5, 'rejected'), (3, 'pending'), (4, 'denied'), (0, 'up'), (1, 'down')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(0, 'state'), (1, 'shell')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (3, '执行中'), (0, '待审批'), (1, '待执行')], default=0),
        ),
    ]
