# Generated by Django 5.1.3 on 2025-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0059_alter_authenticate_type_type_alter_hosts_kernel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_file',
            name='dest_dir',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'LDAP'), (2, 'OAuth'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (1, 'down'), (4, 'denied'), (5, 'rejected'), (3, 'pending'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (0, '待审批'), (2, '已完成'), (1, '待执行')], default=0),
        ),
    ]
