# Generated by Django 5.1.3 on 2025-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0060_transfer_file_dest_dir_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='kernel',
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (1, 'LDAP'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (4, 'denied'), (0, 'up'), (1, 'down'), (5, 'rejected'), (2, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (2, '已完成'), (3, '执行中'), (0, '待审批')], default=0),
        ),
    ]
