# Generated by Django 5.1.3 on 2025-01-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0061_remove_hosts_kernel_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_file',
            name='dest_dir',
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'LDAP'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (2, 'unknown'), (1, 'down'), (3, 'pending'), (4, 'denied'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (0, '待审批'), (1, '待执行'), (2, '已完成')], default=0),
        ),
    ]
