# Generated by Django 5.1.3 on 2025-01-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0062_remove_transfer_file_dest_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_file',
            name='dest_dir',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (1, 'LDAP'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (3, 'pending'), (4, 'denied'), (1, 'down'), (0, 'up'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (0, '待审批'), (2, '已完成'), (3, '执行中')], default=0),
        ),
    ]
