# Generated by Django 5.1.3 on 2025-01-06 09:53

import mirage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0063_transfer_file_dest_dir_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt_master',
            name='sftp_password',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='sftp_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='salt_master',
            name='sftp_user',
            field=mirage.fields.EncryptedCharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'LDAP'), (0, 'Internal'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (4, 'denied'), (2, 'unknown'), (0, 'up'), (1, 'down'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (0, '待审批'), (3, '执行中'), (1, '待执行')], default=0),
        ),
    ]
