# Generated by Django 5.1.3 on 2025-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0065_alter_authenticate_type_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer_file',
            name='dest_dir',
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (1, 'LDAP'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (5, 'rejected'), (3, 'pending'), (4, 'denied'), (1, 'down'), (2, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (1, '待执行'), (0, '待审批'), (2, '已完成')], default=0),
        ),
    ]
