# Generated by Django 5.1.3 on 2025-01-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0067_transfer_file_dest_dir_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (2, 'OAuth'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (5, 'rejected'), (1, 'down'), (2, 'unknown'), (4, 'denied'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (3, '执行中'), (2, '已完成'), (1, '待执行')], default=0),
        ),
    ]
