# Generated by Django 5.1.3 on 2025-03-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0072_task_list_approve_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (0, 'up'), (3, 'pending'), (5, 'rejected'), (4, 'denied')]),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(3, '执行中'), (0, '待审批'), (4, '被拒绝'), (1, '待执行'), (2, '已完成')], default=0),
        ),
    ]
