# Generated by Django 5.1.3 on 2025-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0073_alter_hosts_status_alter_task_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'salt')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (5, 'rejected'), (3, 'pending'), (4, 'denied'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(0, 'state'), (1, 'shell')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (1, '待执行'), (4, '被拒绝'), (3, '执行中'), (0, '待审批')], default=0),
        ),
    ]
