# Generated by Django 5.1.3 on 2025-04-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0074_salt_master_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (2, 'OAuth'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (4, 'denied'), (3, 'pending'), (0, 'up'), (5, 'rejected'), (2, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(0, 'salt'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (3, '执行中'), (0, '待审批'), (4, '被拒绝'), (2, '已完成')], default=0),
        ),
    ]
