# Generated by Django 5.1.3 on 2025-04-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0075_transfer_file_type_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'LDAP'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, 'down'), (2, 'unknown'), (3, 'pending'), (5, 'rejected'), (4, 'denied'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (2, 'playbook'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (3, '执行中'), (4, '被拒绝'), (1, '待执行'), (0, '待审批')], default=0),
        ),
    ]
