# Generated by Django 5.1.3 on 2025-04-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0076_alter_authenticate_type_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (2, 'OAuth'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (1, 'down'), (2, 'unknown'), (3, 'pending'), (4, 'denied'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'salt')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(0, 'state'), (2, 'playbook'), (1, 'shell')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (0, '待审批'), (3, '执行中'), (4, '被拒绝'), (5, '已撤回'), (2, '已完成')], default=0),
        ),
    ]
