# Generated by Django 5.1.3 on 2025-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0077_alter_authenticate_type_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host_group',
            name='type',
            field=models.IntegerField(choices=[(0, 'salt'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(1, 'LDAP'), (2, 'OAuth'), (0, 'Internal')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (1, 'down'), (3, 'pending'), (4, 'denied'), (2, 'unknown'), (0, 'up')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(0, 'salt'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state'), (2, 'playbook')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(4, '被拒绝'), (5, '已撤回'), (1, '待执行'), (2, '已完成'), (0, '待审批'), (3, '执行中')], default=0),
        ),
        migrations.AlterField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
    ]
