# Generated by Django 5.1.3 on 2025-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0078_host_group_type_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(2, 'OAuth'), (0, 'Internal'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='host_group',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (5, 'rejected'), (4, 'denied'), (3, 'pending'), (1, 'down'), (2, 'unknown')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (2, 'playbook'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(0, '待审批'), (2, '已完成'), (5, '已撤回'), (1, '待执行'), (4, '被拒绝'), (3, '执行中')], default=0),
        ),
        migrations.AlterField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
    ]
