# Generated by Django 5.1.3 on 2025-04-22 11:19

import mirage.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0079_alter_authenticate_type_type_alter_host_group_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_group',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(2, 'unknown'), (0, 'up'), (1, 'down'), (4, 'denied'), (3, 'pending'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='password',
            field=mirage.fields.EncryptedTextField(default=''),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='user',
            field=mirage.fields.EncryptedCharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (1, '待执行'), (3, '执行中'), (0, '待审批'), (4, '被拒绝'), (5, '已撤回')], default=0),
        ),
        migrations.AlterField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
    ]
