# Generated by Django 5.1.3 on 2025-04-23 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0080_alter_host_group_type_alter_hosts_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'LDAP'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (1, 'down'), (4, 'denied'), (0, 'up'), (2, 'unknown'), (5, 'rejected')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state'), (2, 'playbook')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(2, '已完成'), (4, '被拒绝'), (1, '待执行'), (3, '执行中'), (5, '已撤回'), (0, '待审批')], default=0),
        ),
        migrations.CreateModel(
            name='chat_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
