# Generated by Django 5.1.3 on 2025-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0082_task_list_repeat_num_alter_authenticate_type_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (2, 'OAuth'), (1, 'LDAP')], default=0),
        ),
        migrations.AlterField(
            model_name='host_group',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(3, 'pending'), (0, 'up'), (2, 'unknown'), (5, 'rejected'), (1, 'down'), (4, 'denied')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (0, 'state'), (2, 'playbook')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(6, '被终止'), (2, '已完成'), (5, '已撤回'), (0, '待审批'), (1, '待执行'), (4, '被拒绝'), (3, '执行中')], default=0),
        ),
        migrations.AlterField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(1, 'ansible'), (0, 'saltstack')], default=0),
        ),
    ]
