# Generated by Django 5.1.3 on 2025-04-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0084_shell_template_extra_vars_shell_template_main_dir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host_group',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(0, 'up'), (1, 'down'), (2, 'unknown'), (5, 'rejected'), (4, 'denied'), (3, 'pending')]),
        ),
        migrations.AlterField(
            model_name='salt_master',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(2, 'playbook'), (0, 'state'), (1, 'shell')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (4, '被拒绝'), (2, '已完成'), (0, '待审批'), (6, '被终止'), (3, '执行中'), (5, '已撤回')], default=0),
        ),
        migrations.AlterField(
            model_name='transfer_file',
            name='type',
            field=models.IntegerField(choices=[(0, 'saltstack'), (1, 'ansible')], default=0),
        ),
        migrations.CreateModel(
            name='sub_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_dir', models.CharField(default='', max_length=300)),
                ('func_content', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='salt.shell_template')),
            ],
        ),
    ]
