# Generated by Django 5.1.3 on 2025-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salt', '0085_alter_host_group_type_alter_hosts_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell_template',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sub_template',
            name='history',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authenticate_type',
            name='type',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'LDAP'), (2, 'OAuth')], default=0),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(5, 'rejected'), (1, 'down'), (3, 'pending'), (2, 'unknown'), (0, 'up'), (4, 'denied')]),
        ),
        migrations.AlterField(
            model_name='shell_template',
            name='type',
            field=models.IntegerField(choices=[(1, 'shell'), (2, 'playbook'), (0, 'state')], default=1),
        ),
        migrations.AlterField(
            model_name='task_list',
            name='status',
            field=models.IntegerField(choices=[(1, '待执行'), (6, '被终止'), (0, '待审批'), (2, '已完成'), (5, '已撤回'), (3, '执行中'), (4, '被拒绝')], default=0),
        ),
    ]
